parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            $translationAPI: '@translation_api'
            $hooksAPI: '@hooks_api'
            $modelInstance: '@model_instance'
            $applicationInfo: '@application_info'
            $modulePathManager: '@module_path_manager'

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    request_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@request_cache_item_pool'

    model_instance:
        class: \PoP\Engine\ModelInstance\ModelInstance
        public: true

    application_info:
        class: \PoP\Engine\Info\ApplicationInfo
        public: true
        arguments:
            $version: '%version%'

    module_filter_manager:
        class: '\PoP\Engine\Managers\ModuleFilterManager'
        public: true
        arguments:
            $modulePathHelpers: '@module_path_helpers'

    module_path_manager:
        class: \PoP\Engine\Managers\ModulePathManager
        public: true

    module_path_helpers:
        class: \PoP\Engine\Managers\ModulePathHelpers
        public: true
            