parameters:
    version: '0.1.0'

services:
    _defaults:
        bind:
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'
            PoP\ComponentModel\Managers\ModulePathManagerInterface: '@module_path_manager'

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    request_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@request_cache_item_pool'

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'
