services:
    _defaults:
        bind:
            PoP\Hooks\HooksAPIInterface: '@hooks_api'
            PoP\Translation\TranslationAPIInterface: '@translation_api'
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    memory_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@memory_cache_item_pool'

    engine:
        class: \PoP\Engine\Engine\Engine
        public: true

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Engine\FieldResolvers\:
        resource: '../src/FieldResolvers/*'
        public: true

    PoP\Engine\RouteModuleProcessors\:
        resource: '../src/RouteModuleProcessors/*'
        public: true

    PoP\Engine\DataStructureFormatters\:
        resource: '../src/DataStructureFormatters/*'
        public: true

    PoP\Engine\DirectiveResolvers\:
        resource: '../src/DirectiveResolvers/*'
        public: true
