services:
    _defaults:
        bind:
            PoP\Hooks\Contracts\HooksAPIInterface: '@hooks_api'
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'
            $modelInstance: '@model_instance'

    request_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@request_cache_item_pool'

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'
