parameters:
    translationAPI: '@translation_api'
    hooksAPI: '@hooks_api'
    modelInstance: '@model_instance'
    applicationInfo: '@application_info'
    moduleFilterManager: '@module_filter_manager'
    modulePathManager: '@module_path_manager'
    modulePathHelpers: '@module_path_helpers'

services:
    _defaults:
        bind:
            $translationAPI: '%translationAPI%'
            $hooksAPI: '%hooksAPI%'
            $modelInstance: '%modelInstance%'
            $applicationInfo: '%applicationInfo%'
            $modulePathManager: '%modulePathManager%'
        public: true

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    request_cache:
        class: \PoP\Engine\Cache\Cache
        arguments:
            $cacheItemPool: '@request_cache_item_pool'

    model_instance:
        class: \PoP\Engine\ModelInstance\ModelInstance

    application_info:
        class: \PoP\Engine\Info\ApplicationInfo
        arguments:
            $version: '0.1.0'

    module_filter_manager:
        class: '\PoP\Engine\ModuleFilters\ModuleFilterManager'
        arguments:
            $modulePathHelpers: '%modulePathHelpers%'

    module_path_manager:
        class: \PoP\Engine\ModulePath\ModulePathManager

    module_path_helpers:
        class: \PoP\Engine\ModulePath\ModulePathHelpers

    # ModuleFilters
    module_filters.head_module:
        class: \PoP\Engine\ModuleFilters\HeadModule
    module_filters.lazy:
        class: \PoP\Engine\ModuleFilters\Lazy
    module_filters.main_content_module:
        class: \PoP\Engine\ModuleFilters\MainContentModule
    module_filters.module_paths:
        class: \PoP\Engine\ModuleFilters\ModulePaths
            