services:
    _defaults:
        bind:
            PoP\Hooks\Contracts\HooksAPIInterface: '@hooks_api'
            PoP\ComponentModel\ModelInstance\ModelInstanceInterface: '@model_instance'
            PoP\ComponentModel\Managers\ModulePathManagerInterface: '@module_path_manager'

    persistent_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@persistent_cache_item_pool'

    memory_cache:
        class: \PoP\Engine\Cache\Cache
        public: true
        arguments:
            $cacheItemPool: '@memory_cache_item_pool'

    PoP\Engine\Hooks\:
        resource: '../src/Hooks/*'
        public: true

    PoP\Engine\ModuleFilters\:
        resource: '../src/ModuleFilters/*'

    PoP\Engine\FieldValueResolvers\:
        resource: '../src/FieldValueResolvers/*'
        public: true
